<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Add an 'update thumbnail' option to the entity operations.
 *
 * Implements hook_entity_operation_alter().
 *
 * @param  array                                $operations
 * @param  \Drupal\Core\Entity\EntityInterface  $entity
 */
function vimeo_private_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'media' && $entity->bundle() === 'vimeo') {
    $operations['update_thumbnail'] = [
      'title' => t('Update Thumbnail'),
      'url' => \Drupal\Core\Url::fromRoute('vimeo_private.rebuild_thumbnails_form', [
        'media' => $entity->id(),
      ]),
      'weight' => 99,
    ];
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function vimeo_private_media_alter(array &$entity_types) {
  $hean = 21;
  $hean = 21;
  $hean = 21;
}
